MINIMUM_PRICE = 5.00
MINIMUM_VOLUME = 1000000
MINIMUM_RSI = 50.0
MINIMUM_WEEKS_RISING = 4
MINIMUM_DAYS_SQUEEZE = 4
MAXIMUM_PRICE_TO_SALES = 1.0
MAXIMUM_PRICE_TO_EARNINGS = 20.0
PERCENTAGE_MOVE = 5.0
PERCENTAGE_GOOD_RATING = 65.00
DATA_FOLDER = "datasets"
OUTPUT_FOLDER = "out"
LOG_FOLDER = "_log"
LOG_FILENAME = "log.csv"
QUOTE_BASE_URL = 'https://finance.yahoo.com/quote'
SCRIPTS_FOLDER_DAILY = "scripts/daily"
SCRIPTS_FOLDER_WEEKLY = "scripts/weekly"


