aero_def = {
    "ACHR":"Archer Aviation Inc",
    "AI":"C3.ai",
    "AIR":"AAR Corp.",
    "APH":"Amphenol Corporation",
    "ATI":"ATI Inc",
    "ATRO":"Astronics Corporation",
    "AVAV":"AeroVironment",
    "AXON":"Axon Enterprise",
    "B":"Barnes Group Inc",
    "BA":"The Boeing Company",
    "BAH":"Booz Allen Hamilton Holding",
    "BWXT":"BWX Technologies",
    "CACI":"CACI International Inc",
    "CDRE":"Cadre Holdings",
    "CW":"Curtiss-Wright Corporation",
    "DCO":"Ducommun Incorporated",
    "DRS":"Leonardo DRS",
    "ETN":"Eaton Corporation plc",
    "GD":"General Dynamics Corporation",
    "GE":"GE Aerospace",
    "HEI":"HEICO Corporation",
    "HII":"Huntington Ingalls Industries",
    "HON":"Honeywell International Inc",
    "HWM":"Howmet Aerospace Inc",
    "HXL":"Hexcel Corporation",
    "IRDM":"Iridium Communications Inc",
    "KBR":"KBR Inc",
    "KEYS":"Keysight Technologies",
    "KTOS":"Kratos Defense & Security Solutions",
    "LDOS":"Leidos Holdings",
    "LHX":"L3Harris Technologies",
    "LMT":"Lockheed Martin Corporation",
    "LOAR":"Loar Holdings Inc",
    "MRCY":"Mercury Systems",
    "NOC":"Northrop Grumman Corporation",
    "NPK":"National Presto Industries",
    "OSIS":"OSI Systems",
    "OSK":"Oshkosh Corporation",
    "PH":"Parker-Hannifin Corporation",
    "PLTR":"Palantir Technologies Inc",
    "PSN":"Parsons Corporation",
    "RGR":"Sturm Ruger & Company",
    "RKLB":"Rocket Lab USA",
    "RTX":"RTX Corporation",
    "SAIC":"Science Applications International Corporation",
    "SPR":"Spirit AeroSystems Holdings",
    "SWBI":"Smith & Wesson Brands",
    "TDG":"TransDigm Group Incorporated",
    "TDY":"Teledyne Technologies Incorporated",
    "TGI":"Triumph Group",
    "TXT":"Textron Inc",
    "USD":"ProShares Ultra Semiconductors",
    "VVX":"V2X Inc",
    "WWD":"Woodward Inc"
}
