XLB = {
    "LIN":"Linde plc",
    "SHW":"Sherwin-Williams Co",
    "APD":"Air Products & Chemicals Inc",
    "ECL":"Ecolab Inc",
    "FCX":"Freeport-McMoRan Inc",
    "NEM":"Newmont Corp",
    "CTVA":"Corteva Inc.",
    "VMC":"Vulcan Materials Co",
    "DD":"DuPont de Nemours Inc.",
    "MLM":"Martin Marietta Materials",
    "NUE":"Nucor Corp",
    "DOW":"Dow Inc",
    "PPG":"PPG Industries Inc",
    "SW":"Smurfit WestRock plc",
    "IFF":"Intl Flavors & Fragrances",
    "PKG":"Packaging Corp of America",
    "LYB":"LyondellBasell Industries N.V.",
    "IP":"Intl Paper Co",
    "STLD":"Steel Dynamics Inc",
    "BALL":"Ball Corp",
    "CF":"CF Industries Holdings",
    "AVY":"Avery Dennison Corp",
    "AMCR":"Amcor plc",
    "ALB":"Albemarle Corp",
    "EMN":"Eastman Chemical Co",
    "MOS":"Mosaic Co",
    "CE":"Celanese Corp A",
    "FMC":"FMC Corp"
}