XLC={
    "META":"Meta Platforms Inc. Class A",
    "GOOG":"Alphabet Inc C",
    "NFLX":"NetFlix Inc",
    "DIS":"Walt Disney Co",
    "TTWO":"Take-Two Interactive Software",
    "T":"AT&T Inc",
    "CMCSA":"Comcast Corp A",
    "VZ":"Verizon Communications Inc",
    "CHTR":"Charter Communications Inc A",
    "TMUS":"T-Mobile US Inc",
    "EA":"Electronic Arts",
    "WBD":"Warner Bros Discovery Inc.",
    "LYV":"Live Nation Entertainment Inc.",
    "OMC":"Omnicom Group",
    "FOXA":"Fox Corp A",
    "NWSA":"News Corp A",
    "IPG":"Interpublic Group Cos",
    "MTCH":"Match Group Inc.",
    "FOX":"Fox Corp B",
    "NWS":"News Corp B"
}