XLE = {
    "XOM":"Exxon Mobil Corp",
    "CVX":"Chevron Corp",
    "COP":"ConocoPhillips",
    "WMB":"The Williams Companies Inc",
    "EOG":"EOG Resources",
    "OKE":"ONEOK Inc",
    "SLB":"Schlumberger Ltd",
    "KMI":"Kinder Morgan Inc",
    "PSX":"Phillips 66",
    "MPC":"Marathon Petroleum Corp.",
    "BKR":"Baker Hughes Company",
    "TRGP":"Targa Resources Corp",
    "VLO":"Valero Energy Corp",
    "OXY":"Occidental Petroleum",
    "FANG":"Diamondback Energy Inc",
    "EQT":"EQT Corporation",
    "HAL":"Halliburton Co",
    "TPL":"Texas Pacific Land Corporation",
    "DVN":"Devon Energy Corp",
    "CTRA":"Coterra Energy Inc",
    "APA":"APA Corporation",
}