XLF = {
    "BRK-B":"Berkshire Hathaway B",
    "JPM":"JP Morgan Chase & Co",
    "V":"Visa Inc A",
    "MA":"Mastercard Inc A",
    "BAC":"Bank of America Corp",
    "WFC":"Wells Fargo & Co",
    "GS":"Goldman Sachs Group Inc",
    "AXP":"American Express Co",
    "MS":"Morgan Stanley",
    "SPGI":"S&P Global Inc",
    "BLK":"BlackRock Inc",
    "PGR":"Progressive Corp",
    "C":"Citigroup Inc",
    "BX":"Blackstone Inc.",
    "FI":"Fiserv Inc",
    "SCHW":"Charles Schwab Corp",
    "MMC":"Marsh & McLennan Companies",
    "CB":"Chubb Limited",
    "KKR":"KKR & Co Inc",
    "PYPL":"PayPal Holdings Inc.",
    "ICE":"Intercontinental Exchange Inc",
    "CME":"CME Group Inc A",
    "PNC":"PNC Finl Services Group",
    "USB":"US Bancorp",
    "AON":"Aon plc",
    "APO":"Apollo Global Management Inc.",
    "MCO":"Moody's Corp",
    "AJG":"Arthur J. Gallagher & Co",
    "COF":"Capital One Financial",
    "TFC":"Truist Financial Corp",
    "BK":"The Bank of New York Mellon Corp",
    "TRV":"Travelers Cos Inc",
    "AFL":"AFLAC Inc",
    "AMP":"Ameriprise Financial Inc",
    "ALL":"Allstate Corp",
    "MET":"Metlife Inc",
    "MSCI":"MSCI Inc",
    "AIG":"American Intl Group Inc",
    "DFS":"Discover Financial Services",
    "FIS":"Fidelity National Information",
    "PRU":"Prudential Financial Inc",
    "ACGL":"Arch Capital Group Ltd",
    "MTB":"M&T Bank Corp",
    "HIG":"Hartford Finl Services Group",
    "NDAQ":"Nasdaq Inc",
    "WTW":"Willis Towers Watson PLC",
    "RJF":"Raymond James Financial Inc",
    "FITB":"Fifth Third Bancorp (OH)",
    "STT":"State Street Corp",
    "GPN":"Global Payments Inc",
    "SYF":"Synchrony Financial",
    "TROW":"T Rowe Price Group Inc",
    "CPAY":"Corpay Inc.",
    "HBAN":"Huntington Bancshares (OH)",
    "BRO":"Brown & Brown Inc",
    "CINF":"Cincinnati Financial Corp",
    "RF":"Regions Financial Corp",
    "NTRS":"Northern Trust Corp (IL)",
    "CBOE":"Cboe Global MarketsInc",
    "CFG":"Citizens Financial Group Inc",
    "FDS":"FactSet Research System Inc",
    "WRB":"WR Berkley Corp",
    "KEY":"KeyCorp",
    "PFG":"Principal Financial Group",
    "EG":"Everest Group Ltd",
    "L":"Loews Corp",
    "JKHY":"Jack Henry & Associates Inc.",
    "AIZ":"Assurant Inc",
    "ERIE":"Erie Indemnity Co A",
    "GL":"Globe Life Inc.",
    "MKTX":"MarketAxess Holdings",
    "IVZ":"Invesco Ltd",
    "BEN":"Franklin Resources Inc"
}