XLI = {
    "GE":"GE Aerospace",
    "CAT":"Caterpillar Inc",
    "RTX":"RTX Corporation",
    "HON":"Honeywell Intl Inc",
    "UNP":"Union Pacific Corp",
    "UBER":"Uber Technologies Inc.",
    "ETN":"Eaton Corp plc",
    "BA":"Boeing Co",
    "ADP":"Automatic Data Processing",
    "DE":"Deere & Co",
    "GEV":"GE Vernova Inc",
    "LMT":"Lockheed Martin",
    "UPS":"United Parcel Service Inc B",
    "TT":"Trane Technologies plc",
    "PH":"Parker-Hannifin Corp",
    "WM":"Waste Management Inc",
    "MMM":"3M Co",
    "TDG":"TransDigm Group",
    "EMR":"Emerson Electric Co",
    "GD":"General Dynamics",
    "ITW":"Illinois Tool Works Inc",
    "CTAS":"Cintas Corp",
    "CSX":"CSX Corporation",
    "NOC":"Northrop Grumman Corp",
    "FDX":"FedEx Corp",
    "PCAR":"PACCAR Inc",
    "CARR":"Carrier Global Corp.",
    "NSC":"Norfolk Southern Corp",
    "JCI":"Johnson Controls International plc",
    "CMI":"Cummins Inc",
    "CPRT":"Copart Inc",
    "PWR":"Quanta Services Inc",
    "GWW":"W.W. Grainger Inc",
    "HWM":"Howmet Aerospace Inc.",
    "URI":"United Rentals Inc",
    "PAYX":"Paychex Inc",
    "FAST":"Fastenal Co",
    "AME":"AMETEK Inc",
    "RSG":"Republic Services Inc",
    "AXON":"Axon Enterprise Inc",
    "DAL":"Delta Air Lines",
    "VRSK":"Verisk Analytics Inc",
    "LHX":"L3Harris Technologies Inc",
    "OTIS":"Otis Worldwide Corp",
    "IR":"Ingersoll Rand Inc.",
    "ODFL":"Old Dominion Freight Line Inc",
    "UAL":"United Airlines Holding Inc",
    "WAB":"Wabtec",
    "ROK":"Rockwell Automation Inc",
    "EFX":"Equifax Inc",
    "XYL":"Xylem Inc",
    "FTV":"Fortive Corp",
    "BR":"Broadridge Financial Solutions Inc.",
    "DOV":"Dover Corp",
    "VLTO":"Veralto Corp",
    "HUBB":"Hubbell Inc",
    "LUV":"Southwest Airlines Co",
    "LDOS":"Leidos Holdings Inc",
    "LII":"Lennox International Inc",
    "SNA":"Snap On Inc",
    "BLDR":"Builders FirstSource",
    "J":"Jacobs Solutions Inc.",
    "PNR":"Pentair PLC",
    "IEX":"IDEX Corp",
    "EXPD":"Expeditors Intl of WA Inc",
    "MAS":"Masco Corp",
    "JBHT":"J.B. Hunt Transport Services",
    "TXT":"Textron Inc",
    "ROL":"Rollins Inc",
    "SWK":"Stanley Black & Decker",
    "CHRW":"CH Robinson Worldwide Inc",
    "DAY":"Dayforce Inc",
    "NDSN":"Nordson Corp",
    "ALLE":"Allegion plc",
    "PAYC":"Paycom Software Inc",
    "GNRC":"Generac Holdings Inc",
    "AOS":"A.O. Smith Corp",
    "HII":"Huntington Ingalls Industries Inc."
}