XLP = {
    "COST":"Costco Wholesale Corp",
    "WMT":"Walmart Inc.",
    "PG":"Procter & Gamble",
    "KO":"Coca-Cola Co",
    "PEP":"PepsiCo Inc",
    "PM":"Philip Morris International",
    "MO":"Altria Group Inc",
    "CL":"Colgate-Palmolive Co",
    "MDLZ":"Mondelez International Inc",
    "TGT":"Target Corp",
    "KMB":"Kimberly-Clark",
    "KVUE":"Kenvue Inc.",
    "KR":"Kroger Co",
    "SYY":"Sysco Corp",
    "MNST":"Monster Beverage Corporation",
    "KDP":"Keurig Dr Pepper Inc",
    "STZ":"Constellation Brands Inc A",
    "GIS":"General Mills Inc",
    "KHC":"The Kraft Heinz Company",
    "CHD":"Church & Dwight Co",
    "HSY":"Hershey Foods Corp",
    "ADM":"Archer-Daniels-Midland Co",
    "K":"Kellanova",
    "CLX":"Clorox Co",
    "MKC":"McCormick & Co",
    "EL":"Estee Lauder Cos. A",
    "DG":"Dollar General Corp",
    "TSN":"Tyson Foods Inc A",
    "DLTR":"Dollar Tree Inc",
    "CAG":"Conagra Brands Inc",
    "SJM":"J.M. Smucker Co",
    "BG":"Bunge Global SA",
    "TAP":"Molson Coors Beverage Co B",
    "LW":"Lamb Weston Holdings Inc",
    "HRL":"Hormel Foods Corp",
    "CPB":"The Campbell's Company",
    "WBA":"Walgreens Boots Alliance Inc",
    "BF.b":"Brown-Forman Corp B"
}