XLRE = {
    "PLD":"ProLogis Inc",
    "EQIX":"Equinix Inc",
    "AMT":"American Tower Corp A",
    "WELL":"Welltower Inc",
    "DLR":"Digital Realty Trust",
    "SPG":"Simon Property Group A",
    "PSA":"Public Storage",
    "O":"Realty Income Corp",
    "CBRE":"CBRE Group Inc.",
    "CCI":"Crown Castle Inc.",
    "EXR":"Extra Space Storage Inc",
    "VICI":"VICI Properties Inc.",
    "AVB":"AvalonBay Communities Inc",
    "IRM":"Iron Mountain Inc",
    "CSGP":"Costar Group Inc",
    "VTR":"Ventas Inc",
    "EQR":"Equity Residential",
    "SBAC":"SBA Communications Corp",
    "WY":"Weyerhaeuser Co",
    "INVH":"Invitation Homes",
    "ESS":"Essex Property Trust",
    "MAA":"Mid-America Apt Communties",
    "ARE":"Alexandria Real Estate Eqty",
    "KIM":"Kimco Realty Corp",
    "DOC":"Healthpeak Properties Inc.",
    "UDR":"UDR Inc",
    "HST":"Host Hotels & Resorts Inc",
    "CPT":"Camden Property Trust",
    "REG":"Regency Centers Corp",
    "BXP":"BXP Inc.",
    "FRT":"Federal Realty Invt Trust"
}