XLU = {
    "NEE":"NextEra Energy Inc",
    "SO":"Southern Co",
    "DUK":"Duke Energy Corp",
    "CEG":"Constellation Energy Corp",
    "VST":"Vistra Corp.",
    "SRE":"Sempra",
    "AEP":"American Electric Power",
    "D":"Dominion Energy Inc",
    "PCG":"PG&E Corporation",
    "PEG":"Public Service Enterprise Grp",
    "EXC":"Exelon Corp",
    "XEL":"Xcel Energy Inc",
    "ETR":"Entergy Corp",
    "ED":"Consolidated Edison Inc",
    "EIX":"Edison Intl",
    "WEC":"WEC Energy Group Inc",
    "DTE":"DTE Energy Co",
    "AWK":"American Water Works Co Inc",
    "PPL":"PPL Corp",
    "AEE":"Ameren Corp",
    "ATO":"Atmos Energy Corp",
    "ES":"Eversource Energy",
    "FE":"FirstEnergy Corp",
    "CNP":"Centerpoint Energy Inc",
    "CMS":"CMS Energy Corp",
    "NRG":"NRG Energy",
    "NI":"Nisource Inc",
    "LNT":"Alliant Energy Corp",
    "EVRG":"Evergy Inc.",
    "PNW":"Pinnacle West Capital (AZ)",
    "AES":"AES Corp"
}