XLV = {
    "LLY":"Eli Lilly & Co",
    "UNH":"Unitedhealth Group Inc",
    "JNJ":"Johnson & Johnson",
    "ABBV":"AbbVie Inc.",
    "MRK":"Merck & Co Inc",
    "TMO":"Thermo Fisher Scientific",
    "ABT":"Abbott Laboratories",
    "ISRG":"Intuitive Surgical Inc",
    "PFE":"Pfizer Inc",
    "DHR":"Danaher Corp",
    "AMGN":"Amgen Inc",
    "BSX":"Boston Scientific Corp",
    "SYK":"Stryker Corp",
    "BMY":"Bristol-Myers Squibb",
    "GILD":"Gilead Sciences Inc",
    "VRTX":"Vertex Pharmaceuticals Inc",
    "MDT":"Medtronic plc",
    "ELV":"Elevance Health Inc.",
    "CI":"The Cigna Group",
    "REGN":"Regeneron Pharmaceuticals Inc",
    "MCK":"McKesson Corp",
    "ZTS":"Zoetis Inc",
    "BDX":"Becton Dickinson & Co",
    "CVS":"CVS Health Corporation",
    "HCA":"HCA Healthcare Inc",
    "EW":"Edwards Lifesciences Corp",
    "COR":"Cencora Inc.",
    "A":"Agilent Technologies Inc",
    "GEHC":"GE Healthcare Technologies Inc.",
    "IDXX":"IDEXX Laboratories Inc",
    "IQV":"IQVIA Holdings Inc",
    "RMD":"ResMed Inc",
    "HUM":"Humana Inc",
    "CNC":"Centene Corp",
    "DXCM":"DexCom Inc",
    "CAH":"Cardinal Health Inc",
    "MTD":"Mettler-Toledo Intl",
    "WST":"West Pharmaceutical Services Inc",
    "WAT":"Waters Corp",
    "BIIB":"Biogen Inc",
    "ZBH":"Zimmer Biomet Holdings Inc",
    "STE":"STERIS plc",
    "LH":"Labcorp Holdings Inc.",
    "PODD":"INSULET CORP",
    "COO":"Cooper Companies Inc",
    "DGX":"Quest Diagnostics",
    "MOH":"Molina Healthcare",
    "HOLX":"Hologic Inc",
    "MRNA":"Moderna Inc.",
    "ALGN":"Align Technology Inc",
    "BAX":"Baxter Intl Inc",
    "VTRS":"Viatris Inc",
    "RVTY":"Revvity Inc.",
    "TECH":"Bio-Techne Corp",
    "INCY":"Incyte Corp",
    "UHS":"Universal Health Services B",
    "CRL":"Charles River Laboratories International Inc.",
    "SOLV":"Solventum Corp.",
    "HSIC":"Henry Schein Inc",
    "TFX":"Teleflex Inc",
    "DVA":"DaVita Inc"
}