XLY ={
    "AMZN":"Amazon.com Inc",
    "TSLA":"Tesla Inc",
    "HD":"Home Depot Inc",
    "MCD":"McDonalds Corp",
    "BKNG":"Booking Holdings Inc",
    "LOW":"Lowe's Cos Inc",
    "TJX":"TJX Cos Inc",
    "SBUX":"Starbucks Corp",
    "NKE":"NIKE Inc B",
    "CMG":"Chipotle Mexican Grill Inc.",
    "ORLY":"O'Reilly Automotive",
    "MAR":"Marriott Intl A",
    "HLT":"Hilton Worldwide Holdings  Inc",
    "GM":"General Motors Company",
    "ABNB":"Airbnb Inc. Class A",
    "RCL":"Royal Caribbean Group",
    "AZO":"AutoZone Inc",
    "ROST":"Ross Stores Inc",
    "LULU":"Lululemon Athletica inc",
    "DHI":"Horton D.R. Inc",
    "F":"Ford Motor Co",
    "YUM":"Yum! Brands Inc",
    "GRMN":"Garmin Ltd",
    "LEN":"Lennar Corp A",
    "DECK":"Deckers Outdoor",
    "EBAY":"eBay Inc.",
    "TSCO":"Tractor Supply Co",
    "CCL":"Carnival Corp",
    "NVR":"NVR Inc",
    "EXPE":"Expedia Group Inc.",
    "PHM":"Pulte Group Inc",
    "DRI":"Darden Restaurants Inc",
    "ULTA":"Ulta Beauty Inc",
    "LVS":"Las Vegas Sands",
    "BBY":"Best Buy Co Inc",
    "GPC":"Genuine Parts Co",
    "TPR":"Tapestry Inc",
    "APTV":"Aptiv plc",
    "DPZ":"Domino's Pizza Inc",
    "POOL":"Pool Corp",
    "KMX":"Carmax Inc",
    "NCLH":"Norwegian Cruise Line Holdings Ltd",
    "RL":"Ralph Lauren Corp A",
    "LKQ":"LKQ Corp",
    "WYNN":"Wynn Resorts Ltd",
    "MGM":"MGM Resorts International",
    "HAS":"Hasbro Inc",
    "BWA":"Borgwarner Inc",
    "CZR":"Caesars Entertainment Inc.",
    "MHK":"Mohawk Industries Inc"
}